name: NodeJS Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # 1️⃣ Checkout the repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js version from the matrix
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 3️⃣ Install dependencies
      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      # 4️⃣ Optional: Start backend server (smoke test)
      - name: Start backend server
        working-directory: ./backend
        run: npm start
